kind: pipeline
type: docker
name: build
steps:
  - name: build
    image: yeasy/docker_practice:latest
    pull: if-not-exists # always never
    environment:
    commands:
      - docker-entrypoint.sh build

trigger:
  branch:
    - master
